### ISSUE TITLE
Some values are not displayed in the reports

### ISSUE THREAD

**Issue by njkim** [archesproject/Arches_HER#768]
1. consultations
url, url label
site visit (observed by, recommended by)

2. heritage asset
associated activities

3. heritage story
location data
administrative area

4. historic aircraft
journey details has 2 flights

**Comment by dwuthrich** [comment]
Heritage Asset report also does not show:

(in Location branch)
Named locations
Land use
Localities/Admin Areas

**Comment by chiatt** [comment]
Named location and land use to be resolved in different PR
