### ISSUE TITLE
Names Scene: Scene shows table even when instance has no names

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/Arches_HER#775]
As shown in the image, the name scene shows an empty table instead of a "no names for this resource" message.

What should happen?  The scene should only show a message (not an empty table) when there are no names associated with a resource![Screen Shot 2022-01-05 at 10.26.17 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/49d55e14-5be5-4904-8170-a6614faa2fab)

**Comment by chiatt** [comment]
Fixed in #778
