### ISSUE TITLE
Update the concept collection "Letters" to match the existing template.

### ISSUE THREAD

**Issue by njkim** [archesproject/Arches_HER#785]
Some letter types in the concept collection "Letters" do not have corresponding templates.
Also, there are some extra templates that do not exist in the concept collection.

So, the concept collection should be updated with currently existing templates.
Or templates should be added.

Missing templates
- Letter G - PXA Approval
- Letter I - Bespoke Letter
- Additional Condition Text
- Archaeological Recommendation Text

Extra templates
- Post Excavation Assessment Approval Letter.docx

**Comment by njkim** [comment]
Concept Collection "Letters" for reference

- Letter A - No Progression
- Letter A2 - No need to consult
- Letter B1 - Pre app predetermination EAS version
- Letter B2 - Predetermination
- Letter C - Condition two stage
- Letter D1 - Pre app recomend condition EAS version
- Letter D2 - Condition investigation
- Letter D3 - Condition historic building recording
- Letter F1 - WSI Approval
- Letter F2 - WSI Amend
- Letter G - PXA Approval
- Letter H - Condition satisfied
- Letter I - Bespoke Letter
- Additional condition text
- Archaeological Recommendations text

**Comment by Philbox** [comment]
@njkim Conditions Scope Notes.docx and Mitigation Scope Notes.docx are jsut documents which provided the scopenotes to add to the collection so do not need templates

**Comment by chiatt** [comment]
@njkim I removed the scope notes files from the issue description

**Comment by StucakeGLHER** [comment]
[Post Excavation Assessment Approval Letter.docx](https://github.com/archesproject/arches-her/files/7970257/Post.Excavation.Assessment.Approval.Letter.docx)
[Blank_Adviser_Letter.docx](https://github.com/archesproject/arches-her/files/7970262/Blank_Adviser_Letter.docx)

@njkim @aj-he Hello,  Here are the two letters you are missing.  The bespoke letter, does not actually exist and it is basically a normal letter with all the headers and footers with space for the advisers to add whatever terxt they want to.  Hopefully the attached makes sense?

**Comment by chiatt** [comment]
Resolved in #890
