### ISSUE TITLE
Geometry in App Area Designation and Protection branch

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#787]
The geometry nodegroup has been removed from the designation and protection branch in most models. It still exists in the Application Area resource model's designation branch. Should it be removed?

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/efce5251-c76d-4362-b87b-6e2303854212)

**Comment by StucakeGLHER** [comment]
@chiatt @aj-he Hi Cyrus, yes please remove the geometry.  We just need to know what designation and protection areas cover the application area as spatially they will be visible either as a stand alone mapping layer or as an exisiting Resource record.  This just duplicates the mapping.

**Comment by Philbox** [comment]
Designation Mapping removed and card changed to default card

**Comment by chiatt** [comment]
Resolved in #d4df102
