### ISSUE TITLE
Hide nodes in App Area designation/protection step?

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#788]
Recent changes to the HER graphs have resulted in an increase in the number of nodes in the Application Area's Designation and Protection step. Should all of these nodes be presented to the user, or should some be hidden to help streamline user input?

https://recordit.co/CnRo4uHj49

**Comment by StucakeGLHER** [comment]
@chiatt @aj-he @Philbox,  Have spoken to one of the Advisers and yes, we don't need all of this for Application Areas.  Please remove: Local Heritage List Critieria Type, Designation Start & End Dates, and Designation Amendment Date.

**Comment by Philbox** [comment]
Branches and nodes removed

**Comment by chiatt** [comment]
Resolved in #d4df102
