### ISSUE TITLE
End date and display date in Site Visit workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#789]
Due to recent graph changes, the first step of the Site Visit workflow now has an 'End Date' and a 'Display Date'. Should these nodes be hidden, or should users be allowed to edit them?

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/31a01f5f-aaad-466a-9ad3-71254d7ceac1)

**Comment by Philbox** [comment]
@chiatt these can be hidden

**Comment by StucakeGLHER** [comment]
@chiatt @aj-he @Philbox Agree.  Hide please.

**Comment by Philbox** [comment]
Site visit card in Consultations model 
![image](https://user-images.githubusercontent.com/16647003/152787393-fcf82b64-2e94-4faa-b4ed-de6ee728ce2d.png)

**Comment by chiatt** [comment]
Resolved in #d4df102
