### ISSUE TITLE
Cardinality n cards with one node and a hidden default node could be cardinality 1

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#790]
Some nodegroups in HER have a concept node and a hidden node with a default value. If the hidden node's default value will always be the same, it might make sense to use a concept list and change the cardinality of the card to 1.

Examples include:
Heritage Story > Language
Activity > Activity Type

The following sql will produce a list of other possible examples:

```
select g.name as graph_name, c.name as card_name, c.nodegroupid as nodegroupid, g.graphid as graphid, nc.count as node_count from (select ng.nodegroupid, count(ng.nodegroupid) as count from node_groups ng 
inner join nodes n on n.nodegroupid = ng.nodegroupid 
where ng.cardinality = 'n' group by ng.nodegroupid) as nc 
inner join cards c on c.nodegroupid = nc.nodegroupid
inner join graphs g on g.graphid = c.graphid
where nc.count = 2
order by g.graphid;
```

**Comment by Philbox** [comment]
Changes made where appropriate
