### ISSUE TITLE
Routing issue with workflows and active-consultations paths

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#793]
**Issue description:** The paths are not working as the /keystone/ path is no longer needed. Paths work with the /keystone/ redirect removed.

**Steps to reproduce:**

1.  Append the following paths to the Keystone URL.

The affected paths are:

```

- /keystone/plugins/application-area

- /keystone/plugins/consultation-workflow

- /keystone/plugins/communication-workflow

- /keystone/plugins/site-visit

- /keystone/plugins/correspondence-workflow

- /keystone/plugins/active-consultations

- /keystone/user

```

**Comment by chiatt** [comment]
@aj-he This issue looks like it may need to be addressed within the Keystone project rather than in the HER repo.

**Comment by aj-he** [comment]
@chiatt @rlwilliamss let me look into this further. Our deployed version is not working but the one I have just built locally is working. Must be to do with the deploy steps. Thanks
