### ISSUE TITLE
How to change the Digital Object to be able to download file

### ISSUE THREAD

**Issue by dymitar** [archesproject/Arches_HER#794]
Hi,
We have a client who wants to use arches (arches-her) project.
I'm new to arches and I'm experimenting with the resource models trying to adjust them according to the clients requests.
We want to change the Digital object model to allow download of the file/s.
I cannot find a way how to achieve this.
Looking at the V5 demo I see the Information Source type, which allows download, but it is using a template called Image Header Template.
Switching the template from digital object in "her" to Image Header Template the file can be downloaded.
But I would like to have the same download feature in Digital Object template, because it is much better for the purpose.
I see the implementation of Digital Object Template but I cannot find how the download is implemented in Image Header template.
Any advice how to do this is highly appreciated.

**Comment by dwuthrich** [comment]
Hi @dymitar This is already possible, just open the card with the file(s) that you wish to download as shown in the attached screen shot.  You can also extend the report template for the digital object to support file downloads (for example in the summary report template accessible in search results).
![Screen Shot 2022-02-01 at 12 38 16 PM](https://user-images.githubusercontent.com/815185/152048808-b9201437-cae7-486b-a5e3-bca2d1fade7c.png)

**Comment by aj-he** [comment]
We are adding the download function to the report so will pick this ticket up.

**Comment by aj-he** [comment]
being picked up as part of #917
