### ISSUE TITLE
National Grid Reference data not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#796]
**Describe the issue** - the National Grid Reference Data is not displaying in the report templates. This is effecting all models.

**Steps to reproduce**

1) Open a record which has NGR data added

2) Click on the Location Data report tab - the NGR data does not display:

![image](https://user-images.githubusercontent.com/78143228/152208032-f709c11f-38ba-43ba-9fda-aabc90a68de2.png)

![image](https://user-images.githubusercontent.com/78143228/152208056-b56ed626-9841-4cb5-8ccf-ef7074dd962e.png)

**Comment by aj-he** [comment]
fixed in #931
