### ISSUE TITLE
Area Assignment under Designation and Protection report section - should be Location Data

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#798]
**Describe the issue -** The Location Data --> Area Assignment is found within the Designation and Protection Status report section rather than the Location Data report section. It should be under Location Data.

**Steps to reproduce**
1) Open a Heritage Asset record in report mode

2) Click on the Designation and Protection Status report tab 

![image](https://user-images.githubusercontent.com/78143228/152210247-3d859441-e7bd-4d2f-bf6c-49daca4c767d.png)

**Comment by aj-he** [comment]
As designed in the spec
