### ISSUE TITLE
Change Artifacts to Artefact in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#799]
Please can this be spelt as Artefacts for consistency.

![image](https://user-images.githubusercontent.com/78143228/152210578-cda5ded0-ed45-4b54-acf8-e2e5b20f4ed1.png)

Also, in the report under the Named Locations section, location is spelled lacation:

![image](https://user-images.githubusercontent.com/78143228/152223762-58086aef-bef2-48ad-b282-c8afaa7d20ef.png)

**Comment by aj-he** [comment]
fixed in #931
