### ISSUE TITLE
Consultation - Relate Related Application Area does not work

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#800]
In the Consultation workflow, when adding an Application Area from the map, clicking on the Relate Related Application Area link returns JavaScript:void(0).

Steps to reproduce

- Open a new Consultation workflow

- In the map editor on step 1 of the workflow, click on an Application Area - resource preview should open

- Click on the Relate Related Application Area link - nothing happens:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/59013689/152210088-9ccdc199-1f0b-499d-bdc7-1a11637cf055.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/59013689/152210131-616a949b-e347-402a-af7a-f7a07df495a4.png">

- After manually linking the Application Area, random floating ‘of’ text (bottom right) and an extra arrow symbol (bottom left) appear:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/59013689/152210378-eaab15c5-a96e-405b-80e2-78b35f79335e.png">

**Comment by chiatt** [comment]
Resolved in #8302
