### ISSUE TITLE
Uploading photos - 'add new' button not working

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#801]
**Describe the issue** - The Add New photo button in the Site Visits - Photographs card does not work when clicked on. There is an additional Add button within the uploaded photographs pane, so the button that doesn't work could just be removed.

**Steps to reproduce**

1) Open a Consultation record in the resource editor

2) Fill out and save the Site Visits card

3) Then click on the Photographs node and upload an image

4) Click on the Add New button in the top right hand corner (highlighted below) - nothing happens. The Add button below the Edit button does work: 

![image](https://user-images.githubusercontent.com/78143228/152211307-f06e6426-bb39-4d5f-9ec4-d131ac210ff6.png)

**Comment by aj-he** [comment]
@rlwilliamss we need to check if this is a core Arches issue. It doesn't look like a part of aher.

**Comment by rlwilliamss** [comment]
@aj-he yes looks like it is, I'll close this and raise it under the core Arches issues.
