### ISSUE TITLE
Consultation - Outcomes options do not fit within radio button set

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#803]
For @Philbox - In the resource editor view for a Consultation record, you are unable to view all the Outcomes as some of them are too long to fit within the div column and the overflow: ellipsis property is used. 
Possibly move the cut off text to a different line underneath, overflow/whitespace properties? Mock-up of solutions to be provided.
Steps to reproduce:
1) Open a Consultation record
2) The record should open in the resource editor
3) Click on the Outcomes card - some of the Outcome options have longer text and you are unable to read the whole text:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/59013689/152212656-523f3fcc-d8a1-4281-99af-5608b9c331ff.png">

We've decided to work around this by converting Planning Outcome and Audit Outcome to single select dropdowns, which do not suffer from truncation with an ellipsis.

**Comment by Philbox** [comment]
Template changed from concept-radio-widget to concept-select-widget. Consultation.json

**Comment by aj-he** [comment]
@rlwilliamss can you check if this is ok and close the ticket if so?

**Comment by rlwilliamss** [comment]
Closing - Consultation Outcomes now concept-select-widget:

![image](https://user-images.githubusercontent.com/78143228/157472601-5ca4f652-59af-4fa8-ba0e-b457b1b9c8cc.png)

**Comment by chrisdolby-HE** [comment]
Closed as fixed.
