### ISSUE TITLE
Designation and Protection reports - reference not displaying the URL

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#804]
**Describe the issue -** In the reports in the Designation and Protection Status tab, the Reference field should show the URL link from the URL for link field in the Designation and Protection Assignment card. Additionally, the Date Qualifier field is empty but I think this should just be removed as there isn't a Date Qualifier field.

**Steps to reproduce**

1) Open a record with Designation and Protection Assignment card e.g., Aircraft

2) Click on the Designation and Protection Status report tab

3) Open the Designation and Protection Details section table by clicking the plus icon to view the Reference field:

![image](https://user-images.githubusercontent.com/78143228/154472469-9f162961-4c90-4dce-b49d-ba6812c5ff47.png)

**Comment by aj-he** [comment]
fixed in #931
