### ISSUE TITLE
Addresses node Sub-Street data not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#806]
**Describe the issue** - The Addresses card Sub-Street node data is not displaying in reports across all models with the node.

**Steps to reproduce**

1) Open a Heritage Asset record with Location Data --> Addresses data added

2) Click on the Location Data report tab

3) Click on the plus icon to view more of the Address data:

![image](https://user-images.githubusercontent.com/78143228/152214565-9d0c21bb-ecbc-400d-a04c-1ae951305ed8.png)

**Data has been added for Sub-Street:**

![image](https://user-images.githubusercontent.com/78143228/152214858-e0199572-adc1-4054-a69f-7278ae7d65b8.png)

**Comment by aj-he** [comment]
fixed in #931
