### ISSUE TITLE
Application Area - only a single related heritage resource can be set

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#807]
For @Philbox - In the Related Heritage Resources step of the Application Area workflow, only a single resource can be related.

This is not intentional, and should allow multiple resources to be selected.

Steps to reproduce

1) Open a new Application Area workflow

2) Enter data for the first 2 steps in the workflow

3) On step 3, Related Heritage Resource, select a resource from the drop-down list
<img width="339" alt="image" src="https://user-images.githubusercontent.com/59013689/152214879-74e419f5-8e28-42e5-ad1f-f150f52584ba.png">
4) Once the resource has been added, select another from the list - this just updates the first resource rather than add an additional resource:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/59013689/152215192-e25fc9c5-7b21-4ffc-8778-e1342719b5b3.png">

**Comment by Philbox** [comment]
Resource instance list enabled and cardinality of card set to 1.

**Comment by aj-he** [comment]
@Philbox just checking that the cardinality should change as that is not mentioned in the ticket?

**Comment by Philbox** [comment]
@aj-he the resource instance list allows for the selection of more than one resource and there are no other attributes (which would necessitate the ability to add another card) so I turned off the allow multiple values. I think that's right....

Option a) Allow multiple values of card:

Use case - If I have 2 assets with different relationships then I want to be able to say:

Asset 1 of Type A is on card 1
Asset 2 of Type B is on card 2

Where Asset and Type are separate nodes

Option b) Allow single card:

Use case - If there are no different relationships then I can say

Asset 1 on card 1
Asset 2 on card 1

Where there is a single node 'Asset'


It's related to issue #786 Single resource instance nodes in a cardinality n nodegroup

**Comment by aj-he** [comment]
Thanks @Philbox

**Comment by Philbox** [comment]
@aj-he does it make sense?

**Comment by Philbox** [comment]
and more importantly does it work in the workflow?

**Comment by aj-he** [comment]
Yes, I see that the card only has a resource instance node in it. Therefore having it as a list will work better for the workflow and making the card 1:1 will mean only one card needs creating

**Comment by aj-he** [comment]
@rlwilliamss can you check and close.

**Comment by chrisdolby-HE** [comment]
Closed as fixed.
