### ISSUE TITLE
Application Area workflow - Related Heritage Resources typos

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#808]
There are typos within the description for Related Heritage Resources.

The text should read:
"Select the other heritage assets, areas, or artefacts related to the current Application Area."

<img width="339" alt="image" src="https://user-images.githubusercontent.com/59013689/152216135-a30565f9-96b0-47d7-b0f6-4f9239285889.png">

**Comment by aj-he** [comment]
I think that we can pick up typos

**Comment by StucakeGLHER** [comment]
@aj-he @chrisdolby-HE Obvs, need to change these to remove Heritage Asset and Heritage Areas.

**Comment by aj-he** [comment]
fixed in #931
