### ISSUE TITLE
Heritage Asset - unable to set multiple evidence types for a construction or use phase

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#809]
For @Philbox - Can only add one Evidence Type – with Construction Phases and Use Phase you can add multiple types:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/59013689/152216680-6646eb07-a270-40c9-a185-086526270652.png">

**Comment by Philbox** [comment]
Datatype updated from Concept to Concept List.

**Comment by Philbox** [comment]
Concept updated to Concept-list

**Comment by aj-he** [comment]
@rlwilliamss can you check and close.

**Comment by chrisdolby-HE** [comment]
Closed as fixed.
