### ISSUE TITLE
Add Bibliographic Source Name report link not working

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#810]
**Describe the issue** - In the Bibliographic Source report, the Add Bibliographic Source Name link under the Bibliographic Source Details tab is not working.

**Steps to reproduce**

1) Open a Bibliographic Source record in report mode

2) With the Bibliographic Source Details report tab open, click on the Add Bibliographic Source Name link:

![image](https://user-images.githubusercontent.com/78143228/152217169-8f18d6fd-7d15-4107-a81f-b32f9ca9e6d0.png)

**Comment by aj-he** [comment]
fixed in #927
