### ISSUE TITLE
Heritage Asset - unable to set more than one cultural period for a construction phase

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#812]
For @Philbox - Construction Phases -> Cultural Period - Can’t seem to add more than one cultural period.  Something can be built across cultural periods. 

We decided that due to the edge case where a phase might legitimately span two periods (rather than being used with uncertainty qualifiers across multiple periods), that it should be possible to add more than one cultural period.

**Comment by Philbox** [comment]
Datatype changed from Resource Instance to Resource Instance List

**Comment by aj-he** [comment]
@rlwilliamss can you check and close.

**Comment by chrisdolby-HE** [comment]
Closed as fixed.
