### ISSUE TITLE
Bibliographic Source - no Name and Identifers tab in report

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#813]
**Describe the issue** - The Bibliographic Source model is missing the Name and Identifiers tab from the report template.

**We just need to clarify this - will remove if name and identifers tab isn't needed.**

**Steps to reproduce**

1) Open a Bibliographic Source record in report mode

2) There is no Name and Identifiers tab in the report

![image](https://user-images.githubusercontent.com/78143228/156590016-e38ca0b0-4589-4e36-966b-275f7e93eea7.png)

**Comment by aj-he** [comment]
fixed in #931
