### ISSUE TITLE
Can the Period Name report tab be moved to the first position

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#816]
**Describe the issue** - Period report re-order - can Period Name be moved to the first position in the report view.

Steps to reproduce

1) Open a Period record in report mode:

![image](https://user-images.githubusercontent.com/78143228/152221612-5ef26d4f-c6ec-4c8a-97cc-d30098aa20e6.png)

**Comment by aj-he** [comment]
fixed in #931
