### ISSUE TITLE
Period - can External Cross References URL be added to report template

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#817]
**Describe the issue** - Period model - the URL added in the External Cross References card does not display in the report template. Please can it be added.

**Steps to reproduce**

1) Open a Period record in report mode

2) Click on the External Cross References report tab - there isn't a URL section under External Cross References

![image](https://user-images.githubusercontent.com/78143228/152222632-94bfe0f5-088c-4cbf-964e-7e44ef6c78ba.png)

**Comment by aj-he** [comment]
fixed in #931
