### ISSUE TITLE
Change order of Addresses card

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#818]
For @Philbox - re-order the Addresses card

Move Building Number down to above Street, so that order is:
Name,
Number Sub-Street,
Sub-Street,
Number,
Street

Locality should also come before Town or City.

**Comment by Philbox** [comment]
Checked and corrected in the following models:
Activity
Application Area
Artefact
Heritage Area
Heritage Asset
Historic Aircraft
Maritime Vessel
Organization
Person
Place

**Comment by aj-he** [comment]
@rlwilliamss please check and close

**Comment by aj-he** [comment]
Closed Complete
