### ISSUE TITLE
Copyright Holder fields -  data not loading

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#819]
For @Philbox - In the Digital Object model Copyright card, when you click on the Copyright Holder drop down field, the data does not load. Also present in the Period Alternative Names Used By field.

**Steps to reproduce**
1) Open this test Digital Object record - https://stage-keystone.historicengland.org.uk/resource/65c363f1-9dd7-4967-81fd-60465f566479#

2) Click on the Copyright card 

3) Click on the Copyright Holder drop down field - the data does not load:

![image](https://user-images.githubusercontent.com/78143228/152224583-95a7889e-2b2e-4b78-bb90-b3eaba3a1680.png)

**Comment by Philbox** [comment]
Copyright Holder resource-instance-list enabled using Person and Organization models. Checked and, where necessary corrected, on the following models:
Archive Source
Artefact
Bibliographic Source
Digital Object

**Comment by aj-he** [comment]
@rlwilliamss please check and close
