### ISSUE TITLE
Geopraphic Coverage card - Geometry node confusion

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#820]
For @Philbox to look at - Not bringing up Geometry as the default landing card, as with Maritime/Aircraft – but in this case it is the only card. Still landing on the top level of the branch then making you navigate a step down to the geometry card.

**Comment by Philbox** [comment]
Heritage Story - Card adjusted so Geographic Coverage and Geometry are on same card so clicking on geographic coverage takes you straight to the map card

**Comment by aj-he** [comment]
@rlwilliamss please check and close
