### ISSUE TITLE
Associated Hertiage Assets/Artefacts/Areas - No way to differentiate when records have same type/name

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#821]
For @Philbox to look into - There is no way to differentiate between Associated Heritage Assets/Artefacts/Areas with same name - when the record is the same i.e. 2 Artefacts with the same name.

**Steps to reproduce**

1) Open this Heritage Asset record - https://stage-keystone.historicengland.org.uk/resource/f313c270-da7d-4d1e-8cf3-34477cd98b73

2) Click on the Associated Heritage Assets/Artefacts/Areas card and click on the drop down

![image](https://user-images.githubusercontent.com/78143228/152225924-618de03b-61f9-4ad7-b462-b8d6a4c81382.png)

**Comment by Philbox** [comment]
I had thought it might be possible to use a grouping card to allow you to see values from more than one card in the Define Resource Descriptors function but the function still only lets you choose from a single card ie. if grouping card include a names card and an identifiers card you can only choose nodes from either names or identifiers. 
What we need to be able to see if the same as we get with node values where we can see more information.

**Comment by aj-he** [comment]
@rlwilliamss please check and close
