### ISSUE TITLE
Heritage Asset - handling links for multiple related resources only works for the first resource

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#822]
Where more than one Record has been linked together, Minas Morgul, Mordor, The One Ring, when you click on them only the first Record is linked.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/59013689/152220869-db2e7881-9d42-4a01-a3da-5011dd1f16ce.png">

**Comment by chiatt** [comment]
Duplicate of #814
