### ISSUE TITLE
Spatial Record Update date fields displaying hours/minutes/seconds

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#823]
For @Philbox - The Spatial Record Update date fields across all models is displaying hours/minutes/seconds - this just needs to be changed to display yyyy-mm-dd.

![image](https://user-images.githubusercontent.com/78143228/152227722-d5ebdb58-5e60-4d45-a7ed-da12262adb83.png)

**Comment by Philbox** [comment]
Checked and corrected in the following models:
Activity
Application Area
Artefact
Place

**Comment by aj-he** [comment]
@rlwilliamss please check and close
