### ISSUE TITLE
Heritage Asset - search window details pane links do not appear to work

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#824]
- Relationships - When the mouse pointer hovers over one of the Resource Record names, the pointer changes to a hand, but when you click on a name nothing hap-pens.  Is this a mistake, or to do with permissions?
<img width="146" alt="image" src="https://user-images.githubusercontent.com/59013689/152227640-e73e5775-6b6b-40d0-bb36-1e0d2bf3292e.png">
- Citations/Source – Similar issue here when you move the mouse pointer over the name: 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/59013689/152227703-06227065-3f71-4684-a6ee-5c5ecb029e7a.png">

**Comment by chrisdolby-HE** [comment]
Can't directly click on the link, but can be opened in new tab/window with right click.

**Comment by aj-he** [comment]
closing as stale
