### ISSUE TITLE
Activity - Associated Files and Associated Heritage Asset/Area/Artefact not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#825]
**Describe the issue** - For Activity records, the Associated Files and Associated Heritage Asset, Area and Artefact data is not displaying in new report templates.

**Steps to reproduce**

1) Open an Activity record with Associated Files and Associated Heritage Asset, Area and Artefact data added

2) Click on the Associated Resources report tab to view the Associated Files section:

![image](https://user-images.githubusercontent.com/78143228/152227989-0a995eeb-0189-410d-97a9-41bd62b1688b.png)

![image](https://user-images.githubusercontent.com/78143228/152228530-0618b979-441b-4cfa-9bdb-364703f28208.png)

**Comment by aj-he** [comment]
fixed in #931
