### ISSUE TITLE
Activity - Archive Material data not displaying in report mode

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#826]
**Describe the issue** - The Activity Archive Material data is not displaying in the report when in the report mode, however it does display in the resource editor report view.

**Steps to reproduce**

1) Open the report for an Activity record with Archive Material data added

2) Click on the Archive Holding tab - the Activity Archive Material section has no data

Report page for the Activity record:

![image](https://user-images.githubusercontent.com/78143228/152229052-b106ddb3-a3f7-4a48-a29d-3d5997c2bf54.png)

Data does display in resource editor:
![image](https://user-images.githubusercontent.com/78143228/152229090-aec32aea-5f1a-4dd5-8a90-a6543bbbf718.png)

**Comment by aj-he** [comment]
fixed in #931
