### ISSUE TITLE
Activity - Location Data report tab does not open

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#827]
**Describe the issue** - When viewing the report for an Activity record, the Location Data tab does not open when clicked on.

**Steps to reproduce**

1) Open an Activity record in report mode

2) Click on the Location Data tab - nothing happens

Location Data tab is blank:

![image](https://user-images.githubusercontent.com/78143228/152229276-257864df-c3eb-4794-a240-4784de4f4075.png)

**Comment by aj-he** [comment]
fixed in #931
