### ISSUE TITLE
Artefact and Activity - duplicates in report sections

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#828]
**Desribe the issue** - When viewing the report for an Artefact record, if you click on each report tab the Discovery section is in every section. 

This is also the same when viewing an Activity record - the Archive Material section is under every tab.

**Steps to reproduce**

1) Open an Artefact or Activity record in report mode

2) Click on each tab to view the data - Archive Material is under each section for Activities, and Dicsovery is in each section for Artefact

![activity-archive-material](https://user-images.githubusercontent.com/78143228/152229582-1b3e2193-2c1f-4fe7-a983-7d2b4db817d9.gif)

**Comment by aj-he** [comment]
closed as stale
