### ISSUE TITLE
Images card - Manage Files/Loaders tab needs clarification

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#829]
**Describe the issue** - In the Heritage Area Images card, when you upload an image, there is a Manage button containing a Manage Files/Loaders tab. We're not sure what this is intended for or whether it was added accidently.

**Steps to reproduce**

1) Open a Heritage Area record

2) Click on the Images card and upload and image

3) Click on the Manage button on the right-hand side to view the Manage Files/Loaders tab:

![image](https://user-images.githubusercontent.com/78143228/152230697-9d437f0b-8439-444b-a1f8-54de9d76b4a7.png)

**Comment by aj-he** [comment]
@rlwilliamss please check and close
