### ISSUE TITLE
Heritage Area - Construction Phase and Evidence data not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#831]
**Describe the issue** - In the Heritage Area model, under the Classifications and Dating report tab, when you click on the Construction Components section to expand it, the Evidence field is empty. Additionally, the Construction Phase field is empty.

**Steps to reproduce** 

1) Open a Heritage Area record with Construction Components --> Evidence data added, and with Construction Phase data added.

2) Click on the Classifications and Dating report tab

3) In the Construction Components section - the Construction Phase and Evidence fields are empty even though data has been added

![image](https://user-images.githubusercontent.com/78143228/152231249-23daac5b-dc3c-4359-bb95-4e4391c4eb53.png)

**Comment by aj-he** [comment]
fixed in #931
