### ISSUE TITLE
Maritime Vessel - scientific date assignment report view incorrect info

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#834]
Scientific Date Assignment report view:
- Start Date of Date Determination is currently displaying the value of Laboratory Reference! Don’t know if the other two are also out of sync as a result? 
It appears that the Dimensions section of the report is looking for Construction Phases rather than the Asset Dimension’s data:
<img width="165" alt="image" src="https://user-images.githubusercontent.com/59013689/152231685-8f9126d3-bf1f-4af0-8cec-99c56f34c3e0.png">

**Comment by rlwilliamss** [comment]
The Scientific Date Assignment data is not displaying the reports. 

Separate bug raised for the Dimensions data not displaying in Maritime report #886.

**Comment by chrisdolby-HE** [comment]
Please note that Scientific Date Assignment is expected on the Assessments tab, not the Classifications and Dating tab shown on the original screenshot. As @rlwilliamss has mentioned, it's not working on the Assessments tab.

**Comment by aj-he** [comment]
fixed in #931
