### ISSUE TITLE
Maritime / Aircraft - geometry should be default landing card for Location

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#835]
For @Philbox - Location
- Not bringing up Geometry as the default landing card

**Comment by Philbox** [comment]
Geometry moved to the top of the card
![image](https://user-images.githubusercontent.com/16647003/152784937-de4c4c46-5236-4559-a42b-bd11ecd7cfbf.png)

**Comment by aj-he** [comment]
@rlwilliamss please check and close

**Comment by aj-he** [comment]
Closed complete
