### ISSUE TITLE
Remove Record Status card

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#836]
For @Philbox - Record Status card is not needed. Only used by us for Activity Records. (There could be an argument for adding this to other Resources, and creating skeleton Records is used by other HERs). Can always be re-added.

**Comment by Philbox** [comment]
Record_Status_Assignment branch removed from the following models:
Artefact

Retained in Activity model.

**Comment by aj-he** [comment]
@rlwilliamss please check and close
