### ISSUE TITLE
Aircraft - remove Flights branch and rename Last Known Flight to Flights

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#837]
For @Philbox - This branch gives the option to record Flight Type as ‘Final’, even though there is an entire other branch for Last Known Flight – can this be taken out of the concept collection to avoid confusion?

**Comment by Philbox** [comment]
Flights branch removed and Crash_Event branch renamed Flights. Card renamed Flights from Last Known Flight.

**Comment by aj-he** [comment]
@rlwilliamss please check and close

**Comment by aj-he** [comment]
This is now complete
