### ISSUE TITLE
Additions to Artefact Dimensions drop-down list

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#840]
For @Philbox - Artefact Dimensions - Need to add ‘pounds’ and ‘ounces’ to the drop-down list

**Comment by Philbox** [comment]
Measurement Units thesaurus and concept collection modified to include new terms. Export of Measurement Units thesaurus and Collections.xml file to be including in next push to 711_grpah_config_fixes

**Comment by aj-he** [comment]
@rlwilliamss please check and close
