### ISSUE TITLE
Aircraft - Flight Type not correct

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#841]
Flight -> Flight Type
- In report mode, this is currently looking at the value of the Date Qualifier node.

**Comment by aj-he** [comment]
There is an oversight on the Flights branch in Historic Aircraft. Following the merge of Flights and Final Flights into a single branch, the node names and cardinality of the Flights card are not correct. Therefore there will need to be an update to the Historic Aircraft model to apply those changes.
