### ISSUE TITLE
Artefact Finders data not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#842]
**Describe the issue** - The Artefact Finders data is not displaying in the report under the Discovery tab.

**Steps to reproduce**

1) Open an Artefact record with Finders data added

2) Click on the Discovery report tab - the Finders data is missing

![image](https://user-images.githubusercontent.com/78143228/152232834-d683b9cc-4065-4bba-b7a3-79c236a6e384.png)

**Comment by aj-he** [comment]
fixed in #931
