### ISSUE TITLE
Artefact report - Discovery tab overlaps with data table

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#843]
**Describe the issue** - In the Artefact report view, the Discovery heading is overlapping with the Discovery data table below it.

**Steps to reproduce**

1) Open an Artefact record in report mode

2) Click on the Discovery tab:

![image](https://user-images.githubusercontent.com/78143228/152233325-3d167879-7908-4249-8562-1b14117205a8.png)

**Comment by aj-he** [comment]
fixed in #928
