### ISSUE TITLE
Heritage Asset - search export issues

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/Arches_HER#844]
Review internally at HE.

- HTML – Construction – The Construction phase/Asset Type is missing. Construction Phases – Asset Type 77e90834-efdc-11eb-b2b9-a87eeabdefba
- Title export – no idea what this is or what it does. Tried using it and get a server error 500.
- CSV - We need to look at the order of the columns as they currently don’t make a lot of sense for Users
- GeoJSON URL - Don’t think this is working properly. Selected 10 Heritage Asset Records and this is what you get when you click the download button:
{"type": "FeatureCollection", "features": []}

and this is when you copy to clipboard:
```
https://stage-keystone.historicengland.org.uk/api/search/export_results?format=geojson&reportlink=false&precision=10&total=5&tiles=true&paging-filter=1&map-filter=%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22id%22%3A%226a410736d700fac5d3e27e897b7b6fc5%22%2C%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%22buffer%22%3A%7B%22width%22%3A%2250000%22%2C%22unit%22%3A%22m%22%7D%2C%22inverted%22%3Afalse%7D%2C%22geometry%22%3A%7B%22coordinates%22%3A%5B-0.1484324089780671%2C51.31386083151119%5D%2C%22type%22%3A%22Point%22%7D%7D%5D%7D&resource-type-filter=%5B%7B%22graphid%22%3A%22076f9381-7b00-11e9-8d6b-80000b44d1d9%22%2C%22name%22%3A%22Heritage%20Asset%22%2C%22inverted%22%3Afalse%7D%5D
```

**Comment by aj-he** [comment]
Being handled internally. Closed
