### ISSUE TITLE
Scientific Date Assignment - need to be able to add multiple instances

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#848]
For @Philbox - In the Scientific Date Assignment card, there is no plus icon to be able to add multiple instances of the card. We should be able to add multiple.

Steps to reproduce

1) Open this Heritage Asset record - `https://stage-keystone.historicengland.org.uk/resource/6ce1c264-27eb-4794-9e3e-fc6887363714#`

2) Click on the Scientific Date Assignment card, you will see an instance of the card has already been added, and there is no plus icon to be able to add another: 

![image](https://user-images.githubusercontent.com/78143228/152366060-9ae6fa42-c298-4022-bf60-ba3989b4ce90.png)

**Comment by Philbox** [comment]
Checked and corrected in:
Artefact
Heritage Asset
Heritage Area
Historic Aircraft
Maritime Vessel

**Comment by aj-he** [comment]
@rlwilliamss please check and close
