### ISSUE TITLE
HLC - Period and Historic Map links not clickable in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#849]
**Describe the issue** - Historic Landscape Characterization model - link text that should link to associated resources in the report template is not doing so, and a list of multiple Periods is being treated as a single entity.

**Steps to reproduce**

1) Open a HLC record with Phase data added

2) On the report, click on the Classifications and Dating tab to view the HLC Phase data

The Period and Historic Map links are not clickable:
![image](https://user-images.githubusercontent.com/78143228/152367479-fdda3466-132a-450e-b86a-04eb47ae666c.png)

**Comment by aj-he** [comment]
fixed in #984
