### ISSUE TITLE
Correspondence workflow letters - update Address

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#850]
**Describe the issue** - Currently, the letter address is looking up Person -> Address -> Full Address, and the term of address is looking up to Person -> Name -> Full Name. 

Would it be possible to redirect these to look at Person -> Contact Details (where Contact Point Type = Mail) -> Contact point for the letter address. 

And Person -> Contact Details (where Contact Point Type = Mail) -> Contact Name for Correspondence for the Name, so that 'Dear Charlie O'Sullivan' would be 'Dear Mr O'Sullivan'.

![image](https://user-images.githubusercontent.com/78143228/152387713-8f710d75-97c2-4659-a784-e77c4c2bbc15.png)

**Comment by chiatt** [comment]
The contact point is a single line of text. It may not always be possible to parse it into a formatted address.

**Comment by dwuthrich** [comment]
We could make the string widget for the address node in the person/organization model a rich-text widget.  That would allow the editor to format the address into multiple lines

**Comment by chiatt** [comment]
@dwuthrich That's a good suggestion. Unfortunately we can't insert html into the Word document, but we could at least use the html to figure out where the line breaks are and then strip the html out of the string.
