### ISSUE TITLE
Correspondence workflow letters - Associated Heritage Assets/Areas/Artefacts not displaying in letter

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#851]
**Describe the issue** - In template letters B onwards, is this meant to be looking up to Associated Heritage Assets, Areas and Artefacts? Or is it for the letter writer to add manually? 

If former, Dennis: could this look-up be fixed, or if the latter, Internal: no real issue but there is a closed square bracket at the end with no corresponding opening bracket that will need to be edited in the letter templates.

![image](https://user-images.githubusercontent.com/78143228/152388534-ef0f9e2d-381a-41fb-8145-72828aee27be.png)

**Example record:**
![image](https://user-images.githubusercontent.com/78143228/152389440-b542da76-3b72-4945-a866-a100216468ae.png)

**Example letter for record:**
![image](https://user-images.githubusercontent.com/78143228/152389360-e13f68c9-bad9-48d8-b120-17e67b96fdde.png)

**Comment by chiatt** [comment]
Resolved in #890
