### ISSUE TITLE
Correspondence workflow letters - F1/F2 address text colour in blue

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#852]
**Describe the issue** - in letter templates F1 – WSI Approval and F2 – WSI Amend, the whole address has been formatted in blue, rather than just the contact’s name. Not sure which is correct but needs to be made consistent.

Also, text being pulled from the model in template letter type B1 - Pre app predetermination EAS version is not being included in bold type. See Desk Based Assessment text below.

![image](https://user-images.githubusercontent.com/78143228/152392760-0fd230dd-3186-4e6e-81fe-56f9f7a8dad0.png)

![image](https://user-images.githubusercontent.com/78143228/152393547-c2bac371-897f-4bb8-9a71-83f45f2463ea.png)

**Comment by rlwilliamss** [comment]
Update - All text in the letters should display in black.

**Comment by chiatt** [comment]
Resolved in #890
