### ISSUE TITLE
Correspondence workflow letters - H Condition Satisfied casework officer phone/email not displaying

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#855]
**Describe the issue** - In letter template H - Condition Satisfied , Casework Officer Email and Direct Dial lookup are not displaying:

![image](https://user-images.githubusercontent.com/78143228/152397309-2c46164e-ef03-4adf-a47a-effa076400d9.png)

**Comment by chiatt** [comment]
Resolved in #890
