### ISSUE TITLE
Activity - Role Type displaying under Role in report

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#860]
**Describe the issue** Activity Role Type is dispalying in the report under Role in Associated People and Organisations, and Role Type is empty. Possibly replace Role (which is showing the correct role type) with Role Type.

**Steps to reprodue**

1) Open an Activity record with Associated People and Organisations data

2) Click on the Associated People and Organisations report tab and expand the table - Role Type value is dispalying under Role and Role Type is empty:

![image](https://user-images.githubusercontent.com/78143228/153411343-fadd95e7-5653-4fd2-890b-a58c0a06f073.png)

![image](https://user-images.githubusercontent.com/78143228/153411403-de374b98-abc2-484c-a755-730e4342bf06.png)

**Comment by aj-he** [comment]
"Role Type" not needed as already in the report as "Role". Remove "Role Type"

**Comment by aj-he** [comment]
fixed in #931
