### ISSUE TITLE
Application Area - Associated Resources not displaying in reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#863]
**Describe the issue** - Application Area - Associated Resources not displaying in reports.#

**Steps to reproduce**

Open an Application Area record in the resource editor with associated resources

Under the Associated Resources report tab, the associated resources are not displaying:

![image](https://user-images.githubusercontent.com/78143228/153418581-a0e719f8-4f38-4e60-a1c7-aab965acd845.png)

**Comment by StucakeGLHER** [comment]
@aj-he Hi Andy.  Looking at the Application Area Name branch, the reason that the currency is not showing could be because that's actually coming from the Address branch.

**Comment by aj-he** [comment]
fixed in #931
