### ISSUE TITLE
Consultation report - add Application Area to Associated Resources section

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#864]
**Describe the issue** - Please can we have Associated Application Area added to the Associated Resources report section for Consultations. 

![image](https://user-images.githubusercontent.com/78143228/153420322-1b01e687-e1dd-4f81-a227-7db5985a6b71.png)

**Comment by aj-he** [comment]
fixed in #931

**Comment by aj-he** [comment]
accidentally reopenned. Will create new ticket.
