### ISSUE TITLE
Application Area - Related Consultations not added under Associated Consultation card

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#865]
When a Consultation workflow is created, and an Application Area is related, when you then open the related Application Area in the resource editor, the Consultation is not added as an Associated Consultation, although it is found under Related Resources. 

Should the related Consultation be added to the Application Area as an Associated Consultation?

@Philbox not sure if this is something you might be able to answer for us.

**Consultation in Application Area as Related Resource:**

![image](https://user-images.githubusercontent.com/78143228/153421427-06bcd920-0636-416b-8d6d-2ae3f531c510.png)

**Consultation is not added as Associated Consultation:**

![image](https://user-images.githubusercontent.com/78143228/153421599-af6cf7a0-a5a0-4edf-91cd-8a805a9d4a17.png)

**Comment by aj-he** [comment]
This is designed behaviour of Arches. Closing
