### ISSUE TITLE
Activity Address Full Name concatenation - order needs changing

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#866]
**Describe the issue** - The Activity Full Name concatenation just needs changing to the new order as per the node ordering:

**Steps to reproduce**

1) Open an Activity record

2) Open the Address card and fill out the fields

3)  Save the card - the Full Name field is concatenated but in the wrong order:

![image](https://user-images.githubusercontent.com/78143228/153560056-887c6c5c-6f99-4179-b95a-77e1f372150b.png)

**Comment by aj-he** [comment]
@rlwilliamss this is a configuration issue for the new node auto populate function. I will change it to match the card.

**Comment by aj-he** [comment]
closed as function config
