### ISSUE TITLE
Consultation reports - JSON-LD does not load

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#870]
**Describe the issue** - Consultation reports under the JSON tab, the JSON-LD does not load when clicked on and arrow does not appear like it does with JSON and Arches JSON

**Steps to reproduce**

1) Open a Consultation record in report mode

2) Click on the JSON tab

3) Click on JSON-LD - it doesn't load

![image](https://user-images.githubusercontent.com/78143228/153582150-0aafc68a-3678-447a-b7c4-8c4b31e48f8c.png)

**Comment by chiatt** [comment]
This could be an issue in core Arches - maybe something to do with generating the JSON-LD for the particular shape/config of the Consultations graph.

**Comment by aj-he** [comment]
@chiatt I have grabbed this error from the logs while replicating. This is using aher Heritage Asset model.

![image](https://user-images.githubusercontent.com/25295526/168306167-19dab5ce-fb6b-40eb-840e-4eb88b7946e7.png)

looks like a bug in core Arches url datatype.

**Comment by chiatt** [comment]
Thanks @aj-he, I see the issue is assigned to you. Would you like me to look into this? Just confirming so we don't duplicate any effort.

**Comment by aj-he** [comment]
@chiatt Sure. It looks like an Arches core bug with the URL datatype rather than something specific in Arches-HER.

**Comment by aj-he** [comment]
fixed in core.. https://github.com/archesproject/arches/issues/9561
