### ISSUE TITLE
Artefact - add Images card to advanced search

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#871]
The Images card needs to be added to the advanced search for the Artefact model following addition of Images card to Artefact model in #838

**Comment by aj-he** [comment]
@Philbox can you check and see if the images node is something that can be added to advanced search? Guessing Stu would be wanting to search for a file name?

**Comment by Philbox** [comment]
Cannot add 'expose to advanced search' on a file-list data type

**Comment by StucakeGLHER** [comment]
@Philbox @aj-he Are we not able to set up imgaes in Artefacts like Photographs for Heritage Assets then?

**Comment by Philbox** [comment]
@StucakeGLHER yes we can. we just need to agree the format for ALL image branches and change them accordingly. If you want all image branches to follow the photo gallery card then we can do that. At the mo they are mixed

**Comment by aj-he** [comment]
@rlwilliamss please check that the captions and copyright nodes are available in advanced search. The file-list node cannot be added to advanced search. If as above please close.
