### ISSUE TITLE
Unable to make a copy of an existing resource

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#874]
**Describe the issue** - When trying to make a copy of most of the records in the resource editor, an error message occurs. One of the resources, battersea Power Station, does copy successfully. 

It seems as though the resources partially copy as they appear in the search results. The resource names are not copied and when you open the copied resources you get a 500 error.

**Steps to reproduce**

1) Open a Heritage Asset record in the resource editor

2) Click on the Manage button and select Copy Resource:

![image](https://user-images.githubusercontent.com/78143228/154931234-9f4bd88e-0350-4337-b0e6-7389bc77dced.png)

3)

**Comment by chiatt** [comment]
@rlwilliamss, does this happen with only some heritage assets or all heritage assets on your system? I haven't been able to reproduce this issue, so I suspect it may be caused by a particular tile saved to the resource. If you open the browser developer tools, do you see a message in the console when this error occurs?

Also, auto-incrementing the Primary Reference Number should probably be in it's own ticket because that modification would be need to be done in the HER repo while the resource copying bug would likely require a fix in the core arches repo.

**Comment by rlwilliamss** [comment]
@aj-he FYI

Hi @chiatt, I've just tried copying each Heritage Asset resource and one of them copies successfully and the other resources have the error - I've added a screenshot of the error to the ticket. It seems like the resources partially copy, as they appear in the search results but you get a server error when opening them and the names are not copied over:

![image](https://user-images.githubusercontent.com/47248246/154928524-55deb521-cd01-40ab-a0aa-f7ec6d1b0f3d.png)

I'll create a separate ticket for auto-incrementing the Primary Reference Number.

**Comment by aj-he** [comment]
@rlwilliamss I am wondering if there is a conflict with the functions? The functions will create tiles based upon other tiles. If the copy process is creating new tiles which trigger functions to generate tiles that already exist then I think there could be a conflict. Let me remove the functions off Heritage Asset in STAGE and retest.

**Comment by aj-he** [comment]
@chiatt @rlwilliamss It looks like functions attached to the models are causing the copy error. This might be a larger issue as there is no obvious way for a function to know that there is a copy operation in progress. The functions will attempt to create new tiles as per the logic built in but this may create a tile that is yet to be copied and saved during the transaction and cause unexpected behaviour.

I will raise an issue against the arches repo to cover the function/copy scenario.  Once a solution has been found there, we can update the functions.

**Comment by aj-he** [comment]
https://github.com/archesproject/arches/issues/8171
