### ISSUE TITLE
Artefact Images card different from other models

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#875]
**Describe the issue** - The Images card in the Artefact model is different to the Images card in other models.

**Steps to reproduce**

1) Open an Artefact record in the resource editor

2) Click on the Images card

3) Upload an image if there isn't one already and then click on the Edit button

The Edit panel does not contain any fields and it does not have the Manage tab:

![image](https://user-images.githubusercontent.com/78143228/153851536-3cee9ece-15b2-4c37-8819-40c194cf48c6.png)

Heritage Area model with correct Edit panel and Manage tab:

![image](https://user-images.githubusercontent.com/78143228/153851739-23bd65eb-d83d-49ab-85b0-1994094ce4f7.png)

**Comment by Philbox** [comment]
Card changed so that caption and copyright appear on the same card instead of separate cards

**Comment by Philbox** [comment]
@aj-he @rlwilliamss the images card for Heritage Asset differs as it uses the Photo Gallery Card, do you want all Images branches to use File Viewer?
![image](https://user-images.githubusercontent.com/16647003/153927541-407b60aa-b56b-4f34-ac0b-e98c673ed22a.png)

**Comment by aj-he** [comment]
@rlwilliamss please check and close
