### ISSUE TITLE
Aircraft - Change Construction Phase Type to select widget

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#876]
**Describe the issue** - The Aircraft Construction Phase -> Construction Phase Type node using the radio button widget, changing to  concept select as per the other models.

@Philbox is making this change.

![image](https://user-images.githubusercontent.com/78143228/153903222-26639afd-149c-431a-952f-8fe99b636dbd.png)

**Comment by Philbox** [comment]
@rlwilliamss This change was made in a previous push. Not sure why this is not showing in your version.

Apologies I hadn't pushed it! pushed now

**Comment by aj-he** [comment]
@rlwilliamss please check and close
