### ISSUE TITLE
Designation and Protection - remove globe icon from report tab

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#878]
**Describe the issue** - Is the globe icon in the Designation and Protection Status report tab, user the Designation/Protection Details section, a link to view the Geometry? If so can we have this removed as the Geometry node was removed from the Designation and Protection Assignment card.

**Steps to reproduce**

1) Open a record that has a Designation and Protection Assignment card e.g., Aircraft

2) Click on the Designation and Protection Status report tab to view the Designation/Protection Details section where the globe icon is:

![image](https://user-images.githubusercontent.com/78143228/154467198-b7fe1c86-f1de-4bfa-b384-03173a3c2bce.png)

**Comment by aj-he** [comment]
fixed in #931
