### ISSUE TITLE
Copy resource - Primary Reference Number does not increment

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#882]
**Describe the issue** - When a resource is copied, the Primary Reference Number value stays the same, this should be auto incremented.

**Steps to reproduce**

1) Open a record in the resource editor

2) Make a copy of the resource

3) In the search results, open the newly copied resource - the Primary Reference Number is the same as the original resource:

Example - Battersea Power Station, the original and both copies have the same Primary Reference Number value:

![image](https://user-images.githubusercontent.com/78143228/154980955-8f913ea4-2068-4b02-abab-6fe627cea4fc.png)

![image](https://user-images.githubusercontent.com/78143228/154981007-0c24c8ec-dcdd-4f77-a4ba-b3820b657627.png)

![image](https://user-images.githubusercontent.com/78143228/154981175-fe2094b6-0ff0-4f9d-9440-0798ae73dbeb.png)

**Comment by aj-he** [comment]
@rlwilliamss this is an internal ticket. Can you close this and create one internally. thx

**Comment by rlwilliamss** [comment]
@aj-he sure will do!
