### ISSUE TITLE
Guest account left navbar shows icons incorrectly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/Arches_HER#883]
Guest users on the search page see buttons in the navbar that they should not, including:

> Manage Resources
> Go to admin view
> Dashboard

What should happen: these navigation items should only be visible to users with credentials

![Screen Shot 2022-02-23 at 11.21.08 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/275f09a2-a0b8-41b9-ad44-37fc3a52a7de)

**Comment by dwuthrich** [comment]
This looks like an artefact of the previous consultations landing page.  When landing on the default Arches search page, the left navbar only shows the search icon, as expected

**Comment by chiatt** [comment]
Hey @dwuthrich The old navbar html should all be gone. @njkim and I only see the default Arches search page, even at `/arches-her/search?paging-filter=1`. Could you see if clearing your cache fixes the issue?
