### ISSUE TITLE
Maritime - Use Phases missing from Classifications and Dating report tab

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#885]
**Describe the issue** - The Use Phase card is missing from the Classifications and Dating report tab in the Maritime model.

Steps to reproduce

1) Open a Maritime record in report mode

2) Click on the Classifications and Dating report tab - the Use Phase is missing

![image](https://user-images.githubusercontent.com/78143228/156585991-f010384e-c459-4460-be64-7f8bb9daf7b5.png)

The Use Phase card in Heritage Asset report view:

![image](https://user-images.githubusercontent.com/78143228/156585284-9765c856-d293-461b-9590-70ab52390410.png)

**Comment by aj-he** [comment]
fixed in #931
