### ISSUE TITLE
Maritime - Scientific Date Assignment Associated Construction Phase related node and relationship to node not set

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#887]
**Describe the issue** - In the Maritime model, the Associated Construction Phase does not load as the related node and relationship to node is not currently set:

![image](https://user-images.githubusercontent.com/78143228/156587960-98c9edf6-10bf-491b-b586-35c65c9c940e.png)

![image](https://user-images.githubusercontent.com/78143228/156588560-d9656e71-a56c-43c4-be6e-4c8097fa0160.png)

**Comment by Philbox** [comment]
Maritime Vessel Type added to node value in scientific dating branch. Updated Maritime_Vessel.json pushed.
@aj-he FYI

**Comment by aj-he** [comment]
@rlwilliamss please check and close
