### ISSUE TITLE
Resource instance list cards display values on a single line

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#888]
**Describe the issue** - For cards using a resource instance list, when multiple values are added, all values are displayed in the card tree on one line. To make it easier to read, it would be nice to have each value displayed on a new line if possible.

Steps to reproduce

1) Open a Heritage Asset record with multiple values added for any of the cards using a resource instance list e.g., Associated Digital Files.

2) You need to drag the card tree to view all the values in the card:

![image](https://user-images.githubusercontent.com/78143228/156620939-ce920599-69a6-4250-a19c-a93645419b6d.png)

**Comment by aj-he** [comment]
@rlwilliamss I think this is a usability issue for core Arches as it is how the resource-instance-list datatype displays in the tree. Can you raise it there, link to it here and then close.

**Comment by rlwilliamss** [comment]
Closing and rasied as a core Arches issue- [https://github.com/archesproject/arches/issues/8228](url)
