### ISSUE TITLE
ConsultationStatus function no longer triggered 

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#898]
It appears that the nodegroupid which had triggered the consultation status function is no longer in the consultation resource model. As a result, the function is no longer called. If it's no longer needed we should remove it, otherwise we should modify its config so that it's triggered by a different nodegroup on the consultation model.

**Comment by StucakeGLHER** [comment]
@chiatt @aj-he Hi,  Just had a look in our Production version of Arches and there is still a branch for Consultation Status  
(6a773228-db20-11e9-b6dd-784f435179ea)?

**Comment by chiatt** [comment]
@StucakeGLHER the status node still exists, but the nodegroupid used to trigger a change in status is no longer in the system. It's still referenced in the function itself as well as the consultation resource model.
https://github.com/archesproject/arches-her/blob/43d3baf1dfb960b2b0336fc56b6fca7701a1b0b9/arches_her/functions/consultation_status_function.py#L25

https://github.com/archesproject/arches-her/blob/43d3baf1dfb960b2b0336fc56b6fca7701a1b0b9/arches_her/pkg/graphs/resource_models/Consultation.json#L8217

**Comment by aj-he** [comment]
@StucakeGLHER the Consultation Status function is looking for a particular card to be saved in order to run. If you put the card name here or a screen shot of the card selected in the resource editor then @chiatt or I can find the nodegroup_id.

**Comment by chrisdolby-HE** [comment]
@aj-he @chiatt Stuart's off today - this is where the card is positioned:

![image](https://user-images.githubusercontent.com/59013689/162159855-2df59ef9-a45a-4ea7-9f4a-cfd8d6c0f492.png)

**Comment by aj-he** [comment]
@chrisdolby-HE it is the card that, when saved, triggers the function to update the status node that is needed.

**Comment by chrisdolby-HE** [comment]
@Philbox Hopefully you can help! I think this is likely one that got replaced last year, when we switched in Actions and Advice. Do you remember which node group this was previously attached to?

**Comment by Philbox** [comment]
@aj-he @chiatt @chrisdolby-HE 
As far as I'm aware this card (above) was added as part of the workflow work. I i don't think it came from me but from an early version that Dennis put together. I'm not sure what card would have triggered the switch from inactive to active but maybe it is the Consultation Type node on the COnsultation Type Grouping Card? 
![image](https://user-images.githubusercontent.com/16647003/162183172-e1c70397-0dab-4f09-86d1-c942736239d4.png)

**Comment by Philbox** [comment]
So when you save the consultation type it triggers the function?

**Comment by chiatt** [comment]
@Philbox probably not. According to the function code, these were the concept labels that would indicate an active status:
  "Mitigation",
  "Post-excavation assessment",
  "Pre-decision assessment/evaluation",
  "Project Initiation",
  "Dormant",
  "Publication & archiving"

I don't see any of these strings in the package anymore. It seems like this function is no longer needed unless there is a different concept that should be used to change the status of a consultation to active. Maybe I should just remove the function for now. If it becomes something we need in the future, we can always restore it.

**Comment by aj-he** [comment]
@Philbox @StucakeGLHER can we agree that this is no longer used due to the graph changes so it can be disabled by @chiatt ?

As stated, if new rules are established to define and Active or Inactive Consultation then the function can be revisited.

**Comment by aj-he** [comment]
closed as fixed in recent v7 upgrade
