### ISSUE TITLE
New Overlay (sub-overlay)

### ISSUE THREAD

**Issue by StucakeGLHER** [archesproject/Arches_HER#901]
@dwuthrich @chiatt @aj-he Hi, could we have a new overlay please?  It would be a sub-overlay of the Heritage Area Resource Model to display just Archaeological Priority Area (APA) types:

- Resource: Heritage Area (979aaf0a-7042-11ea-8a93-287fcf6a5e72)
- Designation and Protection Assignment (a4a81528-efa9-11eb-9abd-a87eeabdefba)
- Designation or Protection Type (a4a816e6-efa9-11eb-b0de-a87eeabdefba)
- Concept Collection: Protection Type = 
•	Archaeological Priority Area, 
•	Archaeological Priority Area – Tier I, 
•	Archaeological Priority Area – Tier II, and
•	Archaeological Priority Area – Tier III

(Heritage_Asset_Node_IDs.jpg)

![Heritage_Area_Node_IDs](https://user-images.githubusercontent.com/26894485/162734711-8ea1c788-cc39-4c16-938d-74933279a9c4.jpg)

We would like the APAs represented in the mapping as they are, to show the different types, in Pro and in the APA survey reports and shapefiles we generated. These reports and shapefiles are supplied to general users, but also to the relevant London Boroughs and to the Greater London Authority for planning purposes, so it is important that they are represented the same way.  Here’s how they are displayed in Pro (please ignore points and lines):
 
(Heritage_Area_APA_Types_ToC.jpg)  
![Heritage_Area_APA_Types_ToC](https://user-images.githubusercontent.com/26894485/162734794-9f6bdd3d-633f-42ec-8ee3-6b93c463a8fa.jpg)

(Heritage_Area_APA_Types_Pro_Mapping.jpg)
![Heritage_Area_APA_Types_Pro_Mapping](https://user-images.githubusercontent.com/26894485/162734816-5eb108e3-25eb-488f-8058-871aaf880667.jpg)

This is need this as the GLAAS Advisers, and the Business Officers, basically use this as their main guide as to whether or not to assign conditions on planning applications, and although this is available in Pro it is not likely that they will have been trained up to use Pro by the time we cut over. Also, from initial discussions, it seems likely that they would prefer to use the mapping in Arches as much as possible. 

Additionally, once we launch in the Autumn, external users will need to be able to easily see the APAs, what they are, and what ‘grade’ they are. This would improve understanding of the implications of any proposed development, and what archaeological work might be needed, before planning applications are submitted, improving their experience of the planning process and help to reduce the workload of the GLAAS Advisers.

**Comment by aj-he** [comment]
Closed as specific GLHER implementation
