### ISSUE TITLE
Letter updates

### ISSUE THREAD

**Issue by StucakeGLHER** [archesproject/Arches_HER#902]
@dwuthrich @njkim @chiatt @aj-he Hi,  Looking through the latest version of Arches we've noticed that the letters are not the current versions being used by GLAAS.  Is it possible to update them please?  I thought I had sent them over earlier in the year, but it is possible that I only sent Letter G:PXA Approval and Letter I - Bespoke. I'm really sorry if I haven’t, and for any extra work this causes. I've attached all the letters just in case.

[Letter A -No progression letter.docx](https://github.com/archesproject/arches-her/files/8464850/Letter.A.-No.progression.letter.docx)
[Letter A2 - No Need to Consult letter.docx](https://github.com/archesproject/arches-her/files/8464851/Letter.A2.-.No.Need.to.Consult.letter.docx)
[Letter B1 - Pre-app Predetermination letter.docx](https://github.com/archesproject/arches-her/files/8464852/Letter.B1.-.Pre-app.Predetermination.letter.docx)
[Letter B2 - Predetermination Letter.docx](https://github.com/archesproject/arches-her/files/8464854/Letter.B2.-.Predetermination.Letter.docx)
[Letter C - Condition Two-Stage Letter.docx](https://github.com/archesproject/arches-her/files/8464855/Letter.C.-.Condition.Two-Stage.Letter.docx)
[Letter D1 - Pre-App Recommend Condition Letter.docx](https://github.com/archesproject/arches-her/files/8464858/Letter.D1.-.Pre-App.Recommend.Condition.Letter.docx)
[Letter D2 - Condition Investigation Letter.docx](https://github.com/archesproject/arches-her/files/8464860/Letter.D2.-.Condition.Investigation.Letter.docx)
[Letter D3 - Condition Historic Building Recording Letter.docx](https://github.com/archesproject/arches-her/files/8464861/Letter.D3.-.Condition.Historic.Building.Recording.Letter.docx)
[Letter F1 - WSI Approval Letter.docx](https://github.com/archesproject/arches-her/files/8464862/Letter.F1.-.WSI.Approval.Letter.docx)
[Letter F2 - WSI Amend Letter.docx](https://github.com/archesproject/arches-her/files/8464863/Letter.F2.-.WSI.Amend.Letter.docx)
[Letter G - Post Excavation Assessment Approval Letter.docx](https://github.com/archesproject/arches-her/files/8464878/Letter.G.-.Post.Excavation.Assessment.Approval.Letter.docx)
[Letter H - Condition Satisfied Letter.docx](https://github.com/archesproject/arches-her/files/8464881/Letter.H.-.Condition.Satisfied.Letter.docx)
[Letter I - Bespoke Letter.docx](https://github.com/archesproject/arches-her/files/8464867/Letter.I.-.Bespoke.Letter.docx)
.

**Comment by aj-he** [comment]
@njkim I am going to get these updated at our end with @StucakeGLHER and then will PR them over to you. This will save you having to reapply the changes you have already made.

**Comment by aj-he** [comment]
closed complete
