### ISSUE TITLE
Consultation Type card overlapping with white space/radio buttons

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#914]
**Describe the bug**
When filling out and saving the Consultation Type card, a white line with what appears to be a radio button is displayed over the card in the card tree on the left hand side.

**To Reproduce**

Open a Consultation record in the resource editor

Click on the Consultation Type card and fill out the fields with any data if there is none already

Save the card - the display of the card changes in the card tree on the left hand side as shown:

**Screenshots**
![image](https://user-images.githubusercontent.com/78143228/165554666-844251ca-ed23-4beb-8793-cc99bcad4ec7.png)

**Comment by rlwilliamss** [comment]
Same as previous issue #659

**Comment by chiatt** [comment]
Hi @rlwilliamss, There was a fix for this merged into core arches (archesproject/arches#8040) and it still looks okay to me. Is it possible that your arches instance isn't running latest in dev/6.1.x or that your browser has the old js file cached?

![image](https://user-images.githubusercontent.com/1877663/165563767-fdb1ea20-0bb7-4e10-ac33-318057598194.png)

**Comment by aj-he** [comment]
@rlwilliamss looks like this fix from fargeo got overwritten during some of the accessibility work. Please raise as a bug on our internal system for this
