### ISSUE TITLE
Reports: Multiple Resources - Associated Resources not displaying in report

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#915]
**Issue Description** - In the report templates, the Associated Resources are not displaying in the Associated Resources report tab.

**Steps to reproduce**

1) Open a record in report mode

2) Click on the Associated Resources report tab - the Associated Resources are not displayed:

![image](https://user-images.githubusercontent.com/78143228/166441980-40225dd0-00a5-4774-8a18-d3922c0070b2.png)

![image](https://user-images.githubusercontent.com/78143228/166442005-18696980-4d99-4c07-a203-eeb356392ac6.png)

**Comment by aj-he** [comment]
fixed in #931
