### ISSUE TITLE
Reports: Multiple resources - Citations not displaying in Descriptions and Citations tab 

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#918]
**Issue Description** - In the report templates - Citations are not displaying in the Descriptions and Citations tab.

Effecting the following models:
- Heritage Story
- Aircraft
- Maritime 

**Steps to reproduce**

1) Open an Aircraft record in report mode

2) Click on the Descriptions and Citations tab

3) Only Descriptions are displayed in the report tab - 

Citations should also display 

![image](https://user-images.githubusercontent.com/78143228/166478662-52296a52-dc43-462c-a781-dd7e4a0732bd.png)

**Comment by aj-he** [comment]
fixed in #950
