### ISSUE TITLE
Reports: Use Phases Start Date displaying End Date value

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#922]
**Issue Description** - Heritage Asset Classification and Dating report tab - Use Phases Start Date is showing the End Date value.

**Steps to reproduce**

1) Open a Heritage Asset record in report mode

2) Click on the Classifications and Dating report tab to view the Construction Components section

3) The Use Phases start date value is displaying as the end date value:

![image](https://user-images.githubusercontent.com/78143228/166684738-4496f686-e95f-4e33-8737-58031b85e1b6.png)

![image](https://user-images.githubusercontent.com/78143228/166684770-4e4522a3-af3a-4861-83ac-cf4ad3b0035e.png)

**Comment by aj-he** [comment]
fixed in #931
