### ISSUE TITLE
Reports: Consultation - 404 error when clicking on a Contact record link

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#923]
**Issue Description** - In the Consultation reports under the Contacts tab, when you click on the links to view the Contact records, a 404 error occurs.

**Steps to reproduce**

1) Open a Consultation record in report mode

2) Click on the Contacts tab and then click on the Contact links: 
e.g., 
Planning Officer: Planning Policy Team
Casework Officer: Adam Single

404 error ocurrs when links are clicked on

![image](https://user-images.githubusercontent.com/78143228/166685571-537cd9ff-c923-4550-8cea-635e30ed4f8f.png)

**Comment by aj-he** [comment]
fixed in #931
