### ISSUE TITLE
Consultation workflow - relate related application area function not configured

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#925]
**Issue Description** - The Relate Related Application Area function is missing from the Consultation GeoJSON step of the Consultation workflow.

**Steps to reproduce**

1) Open a new Consultation workflow

2) In the first step of the workflow, the relate related area function is not configured -

![image](https://user-images.githubusercontent.com/78143228/166969853-cb3e644b-afb5-4a77-9419-8118a12a44bb.png)

Expected result - You should be able to click on an Application Area and relate it from the map:

![image](https://user-images.githubusercontent.com/78143228/166969893-74ee4c0c-f9ea-4dd2-85fe-cc44fd8d4c1c.png)

**Comment by chiatt** [comment]
@rlwilliamss Unfortunately, I'm not able to reproduce this issue. Are you seeing an error in your browsers developer console.

**Comment by aj-he** [comment]
@rlwilliamss I think this is an internal issue. The mapping for Application Area has not loaded so I am thinking there may have been an issue with our pg_featureserv instance.  If this comes up again then please let me know and I'll check.
