### ISSUE TITLE
Add Location Description to Consultation workflow

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#936]
Location Description field/step to be added to the Consultation workflow - like in Application Area workflow

Steps to reproduce

1) Open a new Consultation workflow

2) There is currently no field or step in the Consultation workflow to log a Location Description.

**Add a string node to the location card + hidden type and metatype. "Consultation Location Description".**

**Will need adding to Consultation report templates.**

![image](https://user-images.githubusercontent.com/25295526/167647136-40916d3f-3db5-4c64-883f-b2042d732f0e.png)

**Comment by aj-he** [comment]
@Philbox will do the graph change to add the nodes in. We will need to add the value to the report.

@Philbox once you have done your model work please assign this back to me.
