### ISSUE TITLE
If a consultation is not assigned a geometry, the final step of the consultation workflow fails

### ISSUE THREAD

**Issue by chiatt** [archesproject/Arches_HER#940]
If a consultation is not assigned a geometry, the final step of the consultation workflow fails. If a consultation does not have a geometry, the final step should load as expected, and the map should not be rendered.

**Comment by aj-he** [comment]
@chiatt I am just updating the consultation-final-step to include info on the new Consultation Location Description node. Shall I put a fix in for this? Happy to do it so assign to me if so.

**Comment by chiatt** [comment]
Thanks @aj-he, I actually already addressed it in #941. If you could review my PR, that would be great.
