### ISSUE TITLE
Letters - (logic) duplicate salutation when person has an existing title

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#964]
**Issue description** - When a person has an existing title e.g., Miss or Mr, this then duplicates in the generated Corresspondence letters, so the person title is displayed twice.

**Steps to reproduce**

1) Open a new Corresspondence workflow

2) Search for and select a Consultation record that has a Person record with an exisiting title selected as the contact point for corresspondence e.g., Mr Joe Bloggs

3) Select Letter A  - No Progression as the Letter Type

4) Save the step and once loaded, download the generated letter from the download link

5) Open the letter - the salutation has been duplicated

Examples - 

![image](https://user-images.githubusercontent.com/78143228/169796119-9144a000-9421-4065-b7f3-9abf730c136f.png)

![image](https://user-images.githubusercontent.com/78143228/169796140-aaf86ca2-c1a3-40b1-b94f-b252d6fce613.png)

**Comment by aj-he** [comment]
The issue is with the combination of person Title + Fullname. The Full name often includes the title but not always, which makes things difficult to predict. It has been agreed to use `<Title> <First name> <Last name>`
