### ISSUE TITLE
Application Area missing date nodes from Designation and Protection Assignment

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/Arches_HER#990]
**Issue description -** The Application Area model is missing the date nodes from the Designation and Protection Assignment card

- Start Date
- End Date
- Amendment Date
- Display Date

**Steps to reproduce**

1) Open an Application Area record

2) Click on the Designation and Protection Assignment card - date fields are missing

![image](https://user-images.githubusercontent.com/78143228/173395142-9e9b1fd3-b82e-457f-b1df-d3f2272392d2.png)

![image](https://user-images.githubusercontent.com/78143228/173395246-82a25487-105f-4276-8d74-465279e3448c.png)

**Comment by csmith-he** [comment]
These nodes were removed as part of #788
